
# Um einen Request abzuschicken: Ctrl-Alt R 

# https://example.com/comments/1

# http://www.openligadb.de/api/getmatchdata/bl1/2016/8


### Als JSON Respose
POST http://www.openligadb.de/api/getmatchdata/bl1/2018/22 HTTP/1.1
Accept: content-type: application/json

### Als XML Response
POST http://www.openligadb.de/api/getmatchdata/bl1/2018/22 HTTP/1.1
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
Accept-Language: de,en-US;q=0.7,en;q=0.3
Accept-Encoding: gzip, deflate, br

#### a wenige kuerzer

POST http://www.openligadb.de/api/getmatchdata/bl1/2018/22 HTTP/1.1
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8

### TDKB

#### Liefert eine Liste aller Meisterschaften

GET https://tippdiekistebier.de/betoffice-jweb/bo/office/season/list

### Liefert einer Meisterschaft inklusive der bekannten Spieltage
GET https://tippdiekistebier.de/betoffice-jweb/bo/office/season/28

#### Alle Gruppen zu einer Meisterschaft (hier WM 2018). Interessant bei Welt- oder Europameiterschaft.
https://tippdiekistebier.de/betoffice-jweb/bo/office/season/27/group/all

#### Alle Spiele des Achtelfinals der WM 2018
https://tippdiekistebier.de/betoffice-jweb/bo/office/season/27/group/67/round/all
